name: gdtot_dart
version: 1.0.0
description: A program to convert Gdtot urls to Gdrive
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
